name: Publish Package

on:
  push:
    branches:
      - main
    paths:
      - 'apis/**'

jobs:
  publish-package:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: write
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for git diff
      # fail configuration
      #with:
      #  ref: ${{ github.event.pull_request.head.sha }} # fetch for git diff 

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        check-latest: true
        cache: pnpm
        registry-url: https://npm.pkg.github.com/

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Determine package to publish
      run: |
        changed_files=$(git diff ${{ github.event.before }} ${{ github.event.after }} --name-only --relative=apis/)
        for file in $changed_files; do
          if [[ "$file" == */package.json ]]; then
            file='apis/'$file
            package_name=$(dirname "$file")
            old_version=$(git show ${{ github.event.before }}:"$file" | jq -r '.version')
            new_version=$(git show ${{ github.event.after }}:"$file" | jq -r '.version')
            if [[ "$old_version" != "$new_version" ]]; then
              cd "$package_name"
              pnpm publish
              cd -
            fi
          fi
        done
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
