name: Publish Package

on:
  push:
    branches:
      - main
    paths:
      - 'apis/**'

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      #with:
      #  fetch-depth: 0 # Fetch all history for git diff
      with:
        ref: ${{ github.event.pull_request.head.sha }} # fetch for git diff

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Determine package to publish
      run: |
        changed_files=$(git diff ${{ github.event.before }} ${{ github.event.after }} --name-only --relative=apis/)
        for file in $changed_files; do
          if [[ "$file" == */package.json ]]; then
            file='apis/'$file
            package_name=$(dirname "$file")
            old_version=$(git show ${{ github.event.before }}:"$file" | jq -r '.version')
            new_version=$(git show ${{ github.event.after }}:"$file" | jq -r '.version')
            if [[ "$old_version" != "$new_version" ]]; then
              cd "$package_name"
              pnpm publish
              cd -
            fi
          fi
        done
